[package]
name = "stoatty_term"
version = "0.1.0"
edition.workspace = true
publish.workspace = true

[lints]
workspace = true

[dependencies]
stoatty_protocol = { path = "../tty_protocol" }
alacritty_terminal.workspace = true
memchr.workspace = true
base64.workspace = true
image.workspace = true
flate2.workspace = true
parking_lot.workspace = true
tracing.workspace = true
rustc-hash.workspace = true

[dev-dependencies]
divan = "0.1"

[[bench]]
name = "ingest"
harness = false
