#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum ActionKind {
    Quit,
    SplitRight,
    SplitDown,
    FocusLeft,
    FocusRight,
    FocusUp,
    FocusDown,
    FocusNext,
    FocusPrev,
    ClosePane,
    OpenFile,
    OpenCommandPalette,
    OpenReview,
    AddSelectionBelow,
    MoveLeft,
    MoveRight,
    MoveUp,
    MoveDown,
    MoveNextWordStart,
    MoveNextWordEnd,
    MovePrevWordStart,
}
