[package]
name = "stoat_ast"
version = "0.1.0"
edition = "2024"
readme = "../README.md"
authors = ["Lee Olayvar <leegit@fastmail.com>"]
license-file = "../LICENSE"

[dependencies]
typed-arena = "2.0"
compact_str = "0.8"

[lints]
workspace = true
