[package]
name = "stoat_core"
version = "0.1.0"
edition = "2021"
description = "An bevy based gui for Stoat."
readme = "../README.md"
authors = ["Lee Olayvar <leegit@fastmail.com>"]
license-file = "../LICENSE"

[lib]
name = "stoat_core"
path = "src/lib.rs"

[dependencies]
