[package]
name = "stoat_core"
version = "0.1.0"
edition = "2021"
description = "An bevy based gui for Stoat."
readme = "../README.md"
authors = ["Lee Olayvar <leegit@fastmail.com>"]
license-file = "../LICENSE"

[features]
default = []
csv = ["dep:csv"]
json = ["dep:serde_json"]

[lib]
name = "stoat_core"
path = "src/lib.rs"

[dependencies]
snafu.workspace = true
async-trait.workspace = true
serde.workspace = true
ron = "0.8"
rkyv = { version = "0.8", features = ["indexmap-2", "bytecheck"] }
compact_str = { version = "0.9", features = ["rkyv", "serde"] }
ordered-float = { version = "4.5", features = ["rkyv", "serde"] }
indexmap = { version = "2.7", features = ["serde"] }
csv = { version = "1.3", optional = true }
serde_json = { version = "1.0", optional = true }
