pub mod app;
pub mod command_overlay;
pub mod command_palette;
pub mod dispatch;
pub mod editor_element;
pub mod editor_style;
pub mod editor_view;
pub mod file_finder;
pub mod git_status;
pub mod gutter;
pub mod keybinding_hint;
pub mod keymap_query;
pub mod minimap;
pub mod pane_group;
pub mod render_stats;
pub mod status_bar;
pub mod syntax;

pub use app::run_with_paths;
