[package]
name = "stoat_rope_v2"
version = "0.1.0"
edition = "2024"
readme = "../README.md"
authors = ["Lee Olayvar <leegit@fastmail.com>"]
license-file = "../LICENSE"

[dependencies]
ropey = "1.6"

[lints]
workspace = true
